import math
a = int(input("a= "))
b = int(input("b= "))

print("a + b = ", a+b)
print("a - b = ", a-b)
print("a * b = ", a*b)
print("a // b = ", a//b)
print("a ^ b = ", math.pow(a,b))
print("a % b = ", a%b)
print("a > b", a>b)
print("a < b", a<b)
print("a = b",a == b)
print("a and b", a&b)
print("a or b", a | b)
print("a xor b", a ^ b)
print("not a==b", not(a==b))
print("a >> 1", a>>1)
print("a << 1", a<<1)
